In [1]:
import pandas as pd

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 500)
pd.set_option('display.expand_frame_repr', False)

In [3]:
# Filmler ve kullanıcı puanları iki farklı CSV'den okunuyor
movie = pd.read_csv("datasets/Netflix_Dataset_Movie.csv")
ratings = pd.read_csv("datasets/Netflix_Dataset_Rating.csv")

In [4]:
# Her puanlamaya (rating) karşılık gelen filmin bilgilerini ekliyoruz
df = ratings.merge(movie, how='left', on='Movie_ID')

In [7]:
df['User_ID'].nunique()      # Benzersiz kullanıcı sayısı

143458

In [6]:
df['Movie_ID'].nunique()     # Benzersiz film sayısı

1350

In [8]:
df['Movie_ID'].value_counts().min()   # En az kaç kişi izlemiş

np.int64(1042)

In [9]:
df['Name'].value_counts().max()       # En çok izlenen film sayısı

np.int64(117075)

In [10]:
# Satırlar: Kullanıcılar | Sütunlar: Filmler | Hücreler: Rating değerleri
users_movie_df = df.pivot_table(index=['User_ID'], columns=['Movie_ID'], values='Rating')

In [17]:
#  Rastgele Bir Kullanıcı Seçimi
random_user = int(pd.Series(users_movie_df.index).sample(1, random_state=67))
random_user

C:\Users\smt20\AppData\Local\Temp\ipykernel_8900\2323111293.py:2: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  random_user = int(pd.Series(users_movie_df.index).sample(1, random_state=67))

2447407

In [19]:
random_user_df = users_movie_df[users_movie_df.index == random_user]
random_user_df

Movie_ID  3     8     16    17    18    26    28    30    32    33    44    45    46    47    48    52    55    56    57    58    68    76    77    78    79    83    84    97    104   108   110   111   118   122   127   133   138   143   148   152   156   165   166   167   171   173   175   178   180   181   185   187   188   189   191   197   199   201   208   209   213   215   216   223   225   232   238   239   240   241   242   248   252   253   255   256   257   262   268   269   270   273   275   281   283   285   289   290   295   297   299   304   305   311   312   313   316   329   330   331   334   337   341   344   345   348   353   356   357   358   359   360   361   362   367   371   375   378   381   385   390   393   395   398   400   401   405   406   408   413   416   418   420   422   424   425   426   427   431   432   433   436   438   442   443   445   452   454   456   457   459   463   468   471   473   474   476   477   482   483   486   488   489   494   499   501   504   505   516   517   518   524   528   533   534   535   548   550   551   554   561   563   564   569   571   575   577   579   580   582   585   586   588   599   600   607   615   621   629   631   636   638   643   645   646   652   657   658   659   660   661   662   668   670   672   674   676   677   680   681   682   686   689   692   693   696   700   705   707   708   711   717   720   722   723   725   730   731   732   733   734   746   748   749   750   751   752   754   758   759   760   761   762   763   774   788   789   798   807   808   809   811   817   818   819   822   825   829   831   832   833   840   843   846   850   851   859   862   872   883   886   889   894   895   896   897   900   907   908   918   919   931   937   940   942   952   953   954   956   961   962   963   964   971   977   978   985   986   988   989   990   992   993   994   996   1001  1011  1012  1020  1021  1022  1026  1027  1032  1035  1043  1044  1045  1046  1047  1050  1055  1058  1060  1066  1068  1073  1074  1075  1080  1087  1089  1092  1094  1096  1098  1100  1102  1103  1104  1110  1111  1116  1120  1123  1126  1129  1130  1132  1134  1138  1140  1142  1144  1145  1148  1151  1160  1163  1172  1173  1174  1175  1176  1179  1180  1193  1200  1201  1202  1208  1210  1216  1218  1220  1221  1222  1224  1226  1234  1236  1238  1245  1250  1252  1255  1256  1260  1262  1264  1266  1267  1270  1274  1277  1282  1289  1291  1292  1293  1295  1297  1298  1299  1300  1305  1307  1314  1324  1329  1336  1357  1359  1363  1364  1365  1367  1370  1373  1375  1384  1392  1394  1395  1399  1401  1406  1408  1409  1412  1421  1425  1428  1432  1435  1441  1450  1455  1466  1467  1470  1471  1476  1479  1481  1482  1495  1502  1503  1507  1509  1513  1514  1518  1521  1525  1528  1530  1532  1542  1543  1547  1552  1553  1558  1561  1571  1578  1582  1585  1589  1590  1594  1595  1599  1600  1602  1604  1607  1610  1615  1618  1625  1627  1632  1633  1637  1638  1642  1645  1646  1650  1652  1655  1656  1659  1660  1661  1664  1665  1666  1668  1673  1682  1689  1692  1693  1694  1700  1703  1704  1707  1708  1709  1719  1721  1722  1728  1734  1735  1741  1743  1744  1746  1754  1756  1757  1759  1760  1765  1766  1770  1771  1780  1783  1788  1790  1792  1794  1795  1798  1799  1800  1803  1804  1810  1814  1816  1819  1821  1832  1833  1834  1837  1839  1843  1844  1845  1848  1851  1853  1854  1856  1860  1861  1862  1865  1866  1867  1877  1878  1882  1884  1885  1890  1901  1902  1905  1912  1913  1918  1923  1925  1931  1939  1947  1955  1956  1959  1962  1963  1969  1971  1972  1974  1975  1976  1983  1994  1998  2000  2001  2009  2012  2015  2016  2019  2033  2037  2040  2043  2045  2047  2051  2057  2072  2077  2078  2080  2095  2102  2103  2104  2109  2111  2112  2113  2114  2122  2128  2129  2130  2132  2135  2136  2137  2139  2140  2144  2149  2152  2153  2161  2162  2163  2164  2167  2171  2172  2173  2174  2176  2177  2178  2181  2182  2186  2188  2189  2192  2195  2199  2200  2209  2212  2216  2217  2218  2228  2235  2251  2252  2254  2256  2262  2266  2269  2276  2284  2285  2287  2290  2300  2302  2304  2310  2314  2316  2319  2326  2329  2331  2332  2335  2337  2338  2339  2340  2342  2346  2348  2350  2352  2356  2360  2362  2366  2370  2371  2372  2375  2376  2379  2380  2383  2385  2386  2388  2389  2391  2394  2395  2400  2405  2408  2409  2411  2418  2422  2423  2430  2435  2440  2441  2443  2448  2452  2456  2457  2460  2462  2464  2465  2467  2470  2471  2475  2478  2482  2493  2495  2498  2499  2505  2512  2518  2519  2521  2523  2525  2527  2528  2532  2533  2539  2548  2551  2554  2558  2559  2566  2568  2572  2574  2577  2578  2580  2585  2590  2594  2595  2599  2601  2603  2612  2613  2617  2622  2638  2640  2643  2651  2654  2659  2660  2662  2668  2674  2675  2680  2690  2698  2699  2701  2705  2708  2711  2712  2724  2727  2731  2732  2734  2735  2738  2743  2749  2751  2755  2757  2762  2769  2771  2775  2778  2779  2780  2782  2783  2791  2795  2796  2798  2800  2803  2804  2809  2813  2823  2828  2831  2834  2847  2848  2851  2852  2861  2862  2865  2866  2868  2870  2872  2873  2874  2876  2880  2882  2889  2890  2897  2899  2900  2905  2908  2912  2913  2916  2920  2921  2922  2927  2938  2940  2942  2944  2945  2949  2953  2954  2955  2960  2965  2967  2972  2974  2980  2981  2986  2988  2989  2992  3003  3005  3009  3013  3015  3017  3021  3023  3030  3035  3043  3046  3047  3054  3058  3071  3077  3078  3079  3082  3084  3085  3086  3090  3093  3095  3098  3102  3106  3113  3120  3124  3128  3135  3138  3147  3148  3150  3151  3153  3159  3160  3161  3165  3168  3170  3174  3181  3182  3183  3190  3192  3197  3198  3207  3208  3210  3212  3216  3220  3222  3223  3224  3225  3226  3229  3232  3237  3239  3242  3253  3254  3256  3264  3265  3266  3267  3268  3269  3274  3275  3276  3282  3285  3290  3295  3301  3309  3310  3312  3313  3314  3315  3320  3321  3324  3326  3331  3333  3342  3347  3348  3350  3355  3364  3368  3369  3371  3376  3379  3385  3391  3394  3397  3398  3403  3404  3405  3408  3410  3414  3416  3418  3420  3422  3423  3427  3433  3434  3437  3439  3441  3444  3446  3451  3453  3456  3463  3466  3469  3475  3478  3480  3481  3487  3489  3491  3495  3496  3500  3505  3506  3509  3510  3513  3515  3521  3522  3523  3525  3526  3529  3532  3535  3538  3541  3542  3544  3551  3557  3559  3563  3565  3567  3570  3571  3573  3579  3581  3582  3583  3587  3590  3593  3595  3599  3605  3608  3610  3611  3612  3615  3617  3623  3624  3626  3638  3640  3642  3648  3649  3650  3657  3662  3668  3670  3672  3680  3684  3685  3686  3689  3696  3701  3703  3710  3713  3714  3715  3716  3725  3728  3730  3733  3736  3740  3742  3743  3756  3758  3763  3765  3766  3768  3769  3773  3775  3777  3782  3787  3796  3798  3801  3807  3810  3812  3814  3816  3817  3824  3825  3826  3828  3830  3833  3835  3840  3841  3854  3858  3860  3862  3863  3864  3870  3875  3879  3880  3886  3887  3888  3890  3893  3894  3900  3903  3905  3907  3917  3920  3921  3923  3925  3926  3927  3928  3934  3935  3936  3938  3942  3946  3949  3954  3955  3958  3960  3962  3966  3970  3972  3975  3984  3986  3988  3990  3999  4007  4011  4012  4027  4031  4033  4040  4042  4043  4049  4054  4055  4056  4060  4064  4067  4069  4072  4078  4080  4086  4089  4092  4098  4100  4106  4109  4115  4123  4127  4131  4135  4136  4138  4141  4144  4145  4147  4149  4155  4157  4159  4161  4166  4168  4171  4173  4177  4179  4185  4197  4201  4207  4210  4214  4216  4219  4225  4227  4237  4238  4247  4248  4249  4253  4255  4256  4260  4262  4266  4267  4269  4271  4281  4282  4284  4287  4289  4290  4298  4299  4302  4306  4310  4315  4330  4331  4339  4341  4345  4346  4352  4353  4354  4355  4356  4360  4364  4366  4369  4372  4374  4377  4380  4383  4384  4386  4387  4389  4390  4392  4393  4396  4402  4405  4407  4411  4413  4418  4420  4427  4429  4432  4438  4441  4442  4450  4454  4460  4463  4465  4472  4474  4478  4479  4485  4488  4490  4492  4493  4496
User_ID
2447407    NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   5.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   5.0   NaN   NaN   NaN   2.0   4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN   NaN   NaN   5.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   2.0   NaN   NaN   NaN   NaN   NaN   NaN   5.0   NaN   NaN   NaN   4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   2.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   5.0   NaN   NaN   NaN   2.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   4.0   NaN   2.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   2.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   2.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   2.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   5.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   5.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   5.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   2.0   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   1.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   5.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   5.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   5.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   4.0   NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   5.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN

In [20]:
movies_wacthed = users_movie_df.columns[random_user_df.notna().any().tolist()]
movies_wacthed

Index([30, 197, 270, 299, 312, 313, 457, 474, 758, 862, 908, 985, 1145, 1174, 1180, 1470, 1542, 1703, 1754, 1798, 1865, 1905, 1947, 1962, 2000, 2009, 2178, 2290, 2371, 2452, 2499, 2612, 2660, 2803, 2862, 3079, 3151, 3282, 3350, 3371, 3434, 3522, 3538, 3605, 3624, 3825, 3917, 3938, 3962, 4256, 4262, 4306, 4432, 4472], dtype='int64', name='Movie_ID')

In [21]:
len(movies_wacthed)  # İzlediği film sayısı

54

In [25]:
# Rastgele seçilen kullanıcının izlediği filmlerin %55'inden fazlasını izlemiş kullanıcılar seçilir
same_movie_wacthed = users_movie_df[movies_wacthed]
same_movie_count = same_movie_wacthed.T.notnull().sum().sort_values(ascending=False)
same_movie_count = same_movie_count.reset_index()
same_movie_count

        User_ID   0
0       2447407  54
1       2439493  54
2         16272  54
3        387418  54
4        716173  54
...         ...  ..
143453   956297   0
143454  2101646   0
143455  2122769   0
143456   473435   0
143457  2021849   0

[143458 rows x 2 columns]

In [26]:
perc = len(movies_wacthed) * 50 / 100  # %65 eşik değeri
same_movie_count.columns = ['User_ID', 'Movie_Count']
same_movie_count = same_movie_count[same_movie_count['Movie_Count'] >= perc]['User_ID']
same_movie_count

0        2447407
1        2439493
2          16272
3         387418
4         716173
          ...
36493    1347425
36494     668620
36495     668490
36496    1603271
36497    1347590
Name: User_ID, Length: 36498, dtype: int64

In [27]:
# Ortak İzlenen Filmler Üzerinden Korelasyon Hesaplama
final_df = users_movie_df[users_movie_df.index.isin(same_movie_count)]
final_df

Movie_ID  3     8     16    17    18    26    28    30    32    33    44    45    46    47    48    52    55    56    57    58    68    76    77    78    79    83    84    97    104   108   110   111   118   122   127   133   138   143   148   152   156   165   166   167   171   173   175   178   180   181   185   187   188   189   191   197   199   201   208   209   213   215   216   223   225   232   238   239   240   241   242   248   252   253   255   256   257   262   268   269   270   273   275   281   283   285   289   290   295   297   299   304   305   311   312   313   316   329   330   331   334   337   341   344   345   348   353   356   357   358   359   360   361   362   367   371   375   378   381   385   390   393   395   398   400   401   405   406   408   413   416   418   420   422   424   425   426   427   431   432   433   436   438   442   443   445   452   454   456   457   459   463   468   471   473   474   476   477   482   483   486   488   489   494   499   501   504   505   516   517   518   524   528   533   534   535   548   550   551   554   561   563   564   569   571   575   577   579   580   582   585   586   588   599   600   607   615   621   629   631   636   638   643   645   646   652   657   658   659   660   661   662   668   670   672   674   676   677   680   681   682   686   689   692   693   696   700   705   707   708   711   717   720   722   723   725   730   731   732   733   734   746   748   749   750   751   752   754   758   759   760   761   762   763   774   788   789   798   807   808   809   811   817   818   819   822   825   829   831   832   833   840   843   846   850   851   859   862   872   883   886   889   894   895   896   897   900   907   908   918   919   931   937   940   942   952   953   954   956   961   962   963   964   971   977   978   985   986   988   989   990   992   993   994   996   1001  1011  1012  1020  1021  1022  1026  1027  1032  1035  1043  1044  1045  1046  1047  1050  1055  1058  1060  1066  1068  1073  1074  1075  1080  1087  1089  1092  1094  1096  1098  1100  1102  1103  1104  1110  1111  1116  1120  1123  1126  1129  1130  1132  1134  1138  1140  1142  1144  1145  1148  1151  1160  1163  1172  1173  1174  1175  1176  1179  1180  1193  1200  1201  1202  1208  1210  1216  1218  1220  1221  1222  1224  1226  1234  1236  1238  1245  1250  1252  1255  1256  1260  1262  1264  1266  1267  1270  1274  1277  1282  1289  1291  1292  1293  1295  1297  1298  1299  1300  1305  1307  1314  1324  1329  1336  1357  1359  1363  1364  1365  1367  1370  1373  1375  1384  1392  1394  1395  1399  1401  1406  1408  1409  1412  1421  1425  1428  1432  1435  1441  1450  1455  1466  1467  1470  1471  1476  1479  1481  1482  1495  1502  1503  1507  1509  1513  1514  1518  1521  1525  1528  1530  1532  1542  1543  1547  1552  1553  1558  1561  1571  1578  1582  1585  1589  1590  1594  1595  1599  1600  1602  1604  1607  1610  1615  1618  1625  1627  1632  1633  1637  1638  1642  1645  1646  1650  1652  1655  1656  1659  1660  1661  1664  1665  1666  1668  1673  1682  1689  1692  1693  1694  1700  1703  1704  1707  1708  1709  1719  1721  1722  1728  1734  1735  1741  1743  1744  1746  1754  1756  1757  1759  1760  1765  1766  1770  1771  1780  1783  1788  1790  1792  1794  1795  1798  1799  1800  1803  1804  1810  1814  1816  1819  1821  1832  1833  1834  1837  1839  1843  1844  1845  1848  1851  1853  1854  1856  1860  1861  1862  1865  1866  1867  1877  1878  1882  1884  1885  1890  1901  1902  1905  1912  1913  1918  1923  1925  1931  1939  1947  1955  1956  1959  1962  1963  1969  1971  1972  1974  1975  1976  1983  1994  1998  2000  2001  2009  2012  2015  2016  2019  2033  2037  2040  2043  2045  2047  2051  2057  2072  2077  2078  2080  2095  2102  2103  2104  2109  2111  2112  2113  2114  2122  2128  2129  2130  2132  2135  2136  2137  2139  2140  2144  2149  2152  2153  2161  2162  2163  2164  2167  2171  2172  2173  2174  2176  2177  2178  2181  2182  2186  2188  2189  2192  2195  2199  2200  2209  2212  2216  2217  2218  2228  2235  2251  2252  2254  2256  2262  2266  2269  2276  2284  2285  2287  2290  2300  2302  2304  2310  2314  2316  2319  2326  2329  2331  2332  2335  2337  2338  2339  2340  2342  2346  2348  2350  2352  2356  2360  2362  2366  2370  2371  2372  2375  2376  2379  2380  2383  2385  2386  2388  2389  2391  2394  2395  2400  2405  2408  2409  2411  2418  2422  2423  2430  2435  2440  2441  2443  2448  2452  2456  2457  2460  2462  2464  2465  2467  2470  2471  2475  2478  2482  2493  2495  2498  2499  2505  2512  2518  2519  2521  2523  2525  2527  2528  2532  2533  2539  2548  2551  2554  2558  2559  2566  2568  2572  2574  2577  2578  2580  2585  2590  2594  2595  2599  2601  2603  2612  2613  2617  2622  2638  2640  2643  2651  2654  2659  2660  2662  2668  2674  2675  2680  2690  2698  2699  2701  2705  2708  2711  2712  2724  2727  2731  2732  2734  2735  2738  2743  2749  2751  2755  2757  2762  2769  2771  2775  2778  2779  2780  2782  2783  2791  2795  2796  2798  2800  2803  2804  2809  2813  2823  2828  2831  2834  2847  2848  2851  2852  2861  2862  2865  2866  2868  2870  2872  2873  2874  2876  2880  2882  2889  2890  2897  2899  2900  2905  2908  2912  2913  2916  2920  2921  2922  2927  2938  2940  2942  2944  2945  2949  2953  2954  2955  2960  2965  2967  2972  2974  2980  2981  2986  2988  2989  2992  3003  3005  3009  3013  3015  3017  3021  3023  3030  3035  3043  3046  3047  3054  3058  3071  3077  3078  3079  3082  3084  3085  3086  3090  3093  3095  3098  3102  3106  3113  3120  3124  3128  3135  3138  3147  3148  3150  3151  3153  3159  3160  3161  3165  3168  3170  3174  3181  3182  3183  3190  3192  3197  3198  3207  3208  3210  3212  3216  3220  3222  3223  3224  3225  3226  3229  3232  3237  3239  3242  3253  3254  3256  3264  3265  3266  3267  3268  3269  3274  3275  3276  3282  3285  3290  3295  3301  3309  3310  3312  3313  3314  3315  3320  3321  3324  3326  3331  3333  3342  3347  3348  3350  3355  3364  3368  3369  3371  3376  3379  3385  3391  3394  3397  3398  3403  3404  3405  3408  3410  3414  3416  3418  3420  3422  3423  3427  3433  3434  3437  3439  3441  3444  3446  3451  3453  3456  3463  3466  3469  3475  3478  3480  3481  3487  3489  3491  3495  3496  3500  3505  3506  3509  3510  3513  3515  3521  3522  3523  3525  3526  3529  3532  3535  3538  3541  3542  3544  3551  3557  3559  3563  3565  3567  3570  3571  3573  3579  3581  3582  3583  3587  3590  3593  3595  3599  3605  3608  3610  3611  3612  3615  3617  3623  3624  3626  3638  3640  3642  3648  3649  3650  3657  3662  3668  3670  3672  3680  3684  3685  3686  3689  3696  3701  3703  3710  3713  3714  3715  3716  3725  3728  3730  3733  3736  3740  3742  3743  3756  3758  3763  3765  3766  3768  3769  3773  3775  3777  3782  3787  3796  3798  3801  3807  3810  3812  3814  3816  3817  3824  3825  3826  3828  3830  3833  3835  3840  3841  3854  3858  3860  3862  3863  3864  3870  3875  3879  3880  3886  3887  3888  3890  3893  3894  3900  3903  3905  3907  3917  3920  3921  3923  3925  3926  3927  3928  3934  3935  3936  3938  3942  3946  3949  3954  3955  3958  3960  3962  3966  3970  3972  3975  3984  3986  3988  3990  3999  4007  4011  4012  4027  4031  4033  4040  4042  4043  4049  4054  4055  4056  4060  4064  4067  4069  4072  4078  4080  4086  4089  4092  4098  4100  4106  4109  4115  4123  4127  4131  4135  4136  4138  4141  4144  4145  4147  4149  4155  4157  4159  4161  4166  4168  4171  4173  4177  4179  4185  4197  4201  4207  4210  4214  4216  4219  4225  4227  4237  4238  4247  4248  4249  4253  4255  4256  4260  4262  4266  4267  4269  4271  4281  4282  4284  4287  4289  4290  4298  4299  4302  4306  4310  4315  4330  4331  4339  4341  4345  4346  4352  4353  4354  4355  4356  4360  4364  4366  4369  4372  4374  4377  4380  4383  4384  4386  4387  4389  4390  4392  4393  4396  4402  4405  4407  4411  4413  4418  4420  4427  4429  4432  4438  4441  4442  4450  4454  4460  4463  4465  4472  4474  4478  4479  4485  4488  4490  4492  4493  4496
User_ID
6          NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   4.0   5.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   2.0   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   4.0   NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN   NaN   NaN   5.0   NaN   NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN   NaN   NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN   5.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   2.0   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN   NaN   NaN   NaN   2.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   1.0   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   4.0   NaN   4.0   NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN   NaN   NaN   NaN   5.0   NaN   NaN   1.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN   NaN   NaN   NaN   NaN   3.0   4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN   NaN   NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.0   3.0   NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN   NaN   NaN   NaN   2.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   4.0   NaN   4.0   NaN   NaN   4.0   NaN   NaN   NaN   3.0   NaN   NaN   NaN   NaN   4.0   NaN   NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.0   4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN   NaN   NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN   NaN   3.0   NaN   NaN   NaN   NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.0   3.0   NaN   NaN   NaN   NaN   NaN   3.0   NaN   NaN   NaN   NaN   5.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   5.0   4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN   NaN   5.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN   4.0   3.0   NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN   NaN   NaN   4.0   NaN   NaN   NaN   4.0   NaN   NaN   NaN   NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   1.0   3.0   NaN   NaN   NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN   NaN   NaN   4.0   NaN   NaN   NaN   NaN   NaN   5.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.0   3.0   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   2.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   4.0   4.0   NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.0   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN   NaN   NaN   NaN   4.0   NaN   4.0   NaN   NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN   NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN   NaN   NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   2.0   NaN   NaN   NaN   NaN   NaN   NaN   2.0   NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN   NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   4.0   2.0   NaN   NaN   3.0   NaN   NaN   NaN   NaN   NaN   3.0   NaN   NaN   NaN   NaN   NaN   4.0   4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   4.0   4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   5.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   4.0   4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   1.0   NaN   NaN   4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN

In [1]:
# Kullanıcılar arası korelasyon matrisi hesaplanır
corr_df = final_df.T.corr().unstack().drop_duplicates().sort_values(ascending=False)
corr_df

NameError: name 'final_df' is not defined

In [ ]:
corr_df = pd.DataFrame(corr_df, columns=["corr"])
corr_df.index.names = ['user_id_1', 'user_id_2']
corr_df = corr_df.reset_index()
corr_df

In [ ]:
# Rastgele kullanıcıyla korelasyonu 0.55 üzeri olan kullanıcılar seçilir
top_users = corr_df[(corr_df["corr"] > 0.55) & (corr_df['user_id_1'] == random_user)][['user_id_2', 'corr']]
top_users.columns = ['User_ID', 'Corr']
top_users

In [ ]:
# Bu Kullanıcıların Verdiği Puanlara Ağırlık Ekleme
# Korelasyon katsayısı * rating = ağırlıklı puan
top_users_rating = top_users.merge(ratings, how='left', on='User_ID')
top_users_rating.reset_index(inplace=True)
top_users_rating['weighted_rating'] = top_users_rating['Corr'] * top_users_rating['Rating']

In [ ]:
# En yüksek ağırlıklı puanlara göre sıralama
top_users_rating = top_users_rating.sort_values(by=['weighted_rating'], ascending=False)
top_users_rating.head(10)